# Rename as 'config.properties'
# Public holidays gets checked and updated automatically whenever the config value is called.

[global]
customer = new_world
public_holidays = 2024-01-01,2024-03-21,2024-03-29,2024-04-01,2024-04-27,2024-05-01,2024-05-29,2024-06-17,2024-08-09,2024-09-24,2024-12-16,2024-12-25,2024-12-26,2025-01-01,2025-03-21,2025-04-18,2025-04-21,2025-04-28,2025-05-01,2025-06-16,2025-08-09,2025-09-24,2025-12-16,2025-12-25,2025-12-26,2026-01-01,2026-03-21,2026-04-03,2026-04-06,2026-04-27,2026-05-01,2026-06-16,2026-08-10,2026-09-24,2026-12-16,2026-12-25,2026-12-26

[paths]
timesheet = scratch/timesheet.csv

# create one for each customer in [global] customer
[customer.new_world]
manager = Joe Soap
employees = Jack Daniels, Clip Drift
rate = 500, 600 #for Jack Daniels and Clip Drift respectively
# Taken from jobcode_3 in the tsheet css extraction
jobcode = new_world
manager_sig = True
employee_sig = True
notes = True
weekend = Sat, Sun
ot_rate = {"Mon": 1.5, "Tue": 1.5, "Wed": 1.5, "Thu": 1.5, "Fri": 1.5, "Sat": 1.5, "Sun": 2, "Pub": 2}

[customer.old_world]
manager = Joe Soap
employees = Jack Daniels, Clip Drift
rate = 500, 600 #for Jack Daniels and Clip Drift respectively
# Taken from jobcode_3 in the tsheet css extraction
jobcode = new_world
manager_sig = True
employee_sig = True
notes = True
weekend = Sat, Sun
ot_rate = {"Mon": 1.5, "Tue": 1.5, "Wed": 1.5, "Thu": 1.5, "Fri": 1.5, "Sat": 1.5, "Sun": 2, "Pub": 2}

[gradio]
server_name = 0.0.0.0
server_port = 7860
show_error = True
share = False
show_api = False
